include $(CODE_HOME)/makefile.vars

subsystems:
	$(MAKE) -C console CODE_HOME=$(CODE_HOME)
	$(MAKE) -C service CODE_HOME=$(CODE_HOME)
	$(MAKE) -C service_transport_layer CODE_HOME=$(CODE_HOME)
	$(MAKE) -C pci CODE_HOME=$(CODE_HOME)
	$(MAKE) -C acpi CODE_HOME=$(CODE_HOME)
	$(MAKE) -C apic CODE_HOME=$(CODE_HOME)
	$(MAKE) -C pit CODE_HOME=$(CODE_HOME)
	$(MAKE) -C ata CODE_HOME=$(CODE_HOME)
	$(MAKE) -C network CODE_HOME=$(CODE_HOME)
